services:
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db-test-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    command: >
      sh -c "
      python manage.py migrate --settings=conf.test_settings --noinput &&
      pytest --maxfail=1 --disable-warnings || bash"
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${TEST_SECRET_KEY}
      DATABASE_NAME: ${TEST_DB_NAME}
      DATABASE_USER: ${TEST_DB_USER}
      DATABASE_PASSWORD: ${TEST_DB_PASSWORD}
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      ALLOWED_HOSTS: ${TEST_ALLOWED_HOST}
    depends_on:
      - database
      - redis
    restart: on-failure
    volumes:
      - ./src:/app

volumes:
  db-test-data:
