# Generated by Django 4.0.1 on 2022-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstatistics",
            name="defending_sliding_tackle",
            field=models.IntegerField(),
        ),
    ]
