# Generated by Django 4.0.1 on 2022-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_value_eur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_positions',
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='long_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_position',
            field=models.CharField(max_length=100),
        ),
    ]
