# Generated by Django 4.0.1 on 2022-04-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_crossing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_finishing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_heading_accuracy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_short_passing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_volleys',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defending',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defending_marking',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defending_sliding_tackle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='defending_standing_tackle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='dribbling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mentality_aggression',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mentality_interceptions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mentality_penalties',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mentality_positioning',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mentality_vision',
        ),
        migrations.RemoveField(
            model_name='player',
            name='movement_acceleration',
        ),
        migrations.RemoveField(
            model_name='player',
            name='movement_agility',
        ),
        migrations.RemoveField(
            model_name='player',
            name='movement_balance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='movement_reactions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='movement_sprint_speed',
        ),
        migrations.RemoveField(
            model_name='player',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pace',
        ),
        migrations.RemoveField(
            model_name='player',
            name='passing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='physic',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_jumping',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_long_shots',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_shot_power',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_stamina',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_strength',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shooting',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skill_ball_control',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skill_curve',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skill_dribbling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skill_fk_accuracy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='skill_long_passing',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='value_eur',
        ),
        migrations.AlterModelTable(
            name='player',
            table=None,
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team_position', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('value_eur', models.IntegerField()),
                ('pace', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('physic', models.IntegerField()),
                ('attacking_crossing', models.IntegerField()),
                ('attacking_finishing', models.IntegerField()),
                ('attacking_heading_accuracy', models.IntegerField()),
                ('attacking_short_passing', models.IntegerField()),
                ('attacking_volleys', models.IntegerField()),
                ('skill_dribbling', models.IntegerField()),
                ('skill_curve', models.IntegerField()),
                ('skill_fk_accuracy', models.IntegerField()),
                ('skill_long_passing', models.IntegerField()),
                ('skill_ball_control', models.IntegerField()),
                ('movement_acceleration', models.IntegerField()),
                ('movement_sprint_speed', models.IntegerField()),
                ('movement_agility', models.IntegerField()),
                ('movement_reactions', models.IntegerField()),
                ('movement_balance', models.IntegerField()),
                ('power_shot_power', models.IntegerField()),
                ('power_jumping', models.IntegerField()),
                ('power_stamina', models.IntegerField()),
                ('power_strength', models.IntegerField()),
                ('power_long_shots', models.IntegerField()),
                ('mentality_aggression', models.IntegerField()),
                ('mentality_interceptions', models.IntegerField()),
                ('mentality_positioning', models.IntegerField()),
                ('mentality_vision', models.IntegerField()),
                ('mentality_penalties', models.IntegerField()),
                ('defending_marking', models.IntegerField()),
                ('defending_standing_tackle', models.IntegerField()),
                ('defending_sliding_tackle', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
