# Generated by Django 4.0.1 on 2022-04-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_player_age_remove_player_attacking_crossing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='long_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='club',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playerstatistics',
            name='team_position',
            field=models.TextField(),
        ),
    ]
