name: CI Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Serwisy uruchamiane w GitHub Actions
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.TEST_DB_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: conf.test_settings
      POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
      POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: 5432
      ALLOWED_HOSTS: ${{ secrets.TEST_ALLOWED_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.TEST_DB_USER }}; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run migrations
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings

      - name: Comment PR with test results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: result.log