name: CI Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.TEST_ALLOWED_HOST }}
      DJANGO_SETTINGS_MODULE: conf.test_settings
      DATABASE_URL: postgres://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@localhost:5432/${{ secrets.TEST_DB_NAME }}

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${POSTGRES_USER}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run migrations and tests
        run: |
          python manage.py migrate --noinput
          pytest --maxfail=1 --disable-warnings

      - name: Comment PR with test results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: result.log
